# Site settings
title: Jack Yates
email: j.yates.13+bl@googlemail.com
timezone: Europe/London
description: > # this means to ignore newlines until "baseurl:"
  My personal website/blog. Very much a work in progress...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jackyates.co.uk" # the base hostname & protocol for your site
twitter_username: j_yates_13
github_username:  jyates13

# Build settings
markdown: kramdown
